spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/seller_price_monitoring
    username: seller_price_monitoring
    password: seller_price_monitoring
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.web: info
